run:
	docker run --rm -it --name verdaccio -v /home/mike/git/objectiv-analytics/tracker/verdaccio/config.yaml:/verdaccio/conf/config.yaml -p 4873:4873 --network verdaccio verdaccio/verdaccio:5

stop:
	docker stop verdaccio
