/*
 * Copyright 2022 Objectiv B.V.
 */

/**
 * GlobalContext error types
 */
export enum GlobalContextErrorType {
  GLOBAL_CONTEXT_MISSING = 'GLOBAL_CONTEXT_MISSING',
  GLOBAL_CONTEXT_DUPLICATED = 'GLOBAL_CONTEXT_DUPLICATED',
}

/**
 * LocationContext error types
 */
export enum LocationContextErrorType {
  LOCATION_CONTEXT_MISSING = 'LOCATION_CONTEXT_MISSING',
  LOCATION_CONTEXT_DUPLICATED = 'LOCATION_CONTEXT_DUPLICATED',
  LOCATION_CONTEXT_WRONG_POSITION = 'LOCATION_CONTEXT_WRONG_POSITION',
}
